export const styles = {
    editorContainer: {
      position: 'absolute' as const,
      left: 0,
      top: '50%',
      transform: 'translateY(-50%)',
      zIndex: 5,
      width: '40px',
      height: '100%',
    },
    buttonContainer: {
      position: 'absolute' as const,
      left: '8px',
      top: '50%',
      transform: 'translateY(-50%)',
      zIndex: 5,
      transition: 'opacity 0.2s ease-in-out',
    },
    buttonGroup: {
      display: 'flex',
      flexDirection: 'column' as const,
      gap: '8px',
    },
    actionButton: {
      padding: '4px',
      borderRadius: '4px',
      cursor: 'pointer',
      background: 'white',
      boxShadow: '0 2px 4px rgba(0,0,0,0.1)',
      transition: 'box-shadow 0.1s ease',
    },
    modalOverlay: {
      position: 'fixed' as const,
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      zIndex: 9999,
      pointerEvents: 'auto' as const,
    },
    modalContainer: {
      position: 'absolute' as const,
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      pointerEvents: 'none' as const,
      zIndex: 10000,
    },
    modalContent: {
      pointerEvents: 'auto' as const,
      zIndex: 10001,
    },
  };