export const styles = {
    cardBase: {
      width: '100%',
      height: '100%',
      backgroundColor: '#FFFFFF',
      boxShadow: '0px 10px 15px -3px rgba(0, 0, 0, 0.25), 0px 4px 6px -4px rgba(0, 0, 0, 0.1)',
      borderRadius: '8px',
      padding: '24px',
      display: 'flex',
      flexDirection: 'column' as const,
      position: 'relative' as const,
      overflowY: 'hidden' as const,
      boxSizing: 'border-box' as const,
    },
    sectionHeader: {
      width: '100%',
      textAlign: 'center' as const,
      marginBottom: '16px',
    },
    headerLabel: {
      fontFamily: 'Inter',
      fontStyle: 'normal',
      fontWeight: 300,
      fontSize: '20px',
      lineHeight: '24px',
      color: '#64748B',
      textTransform: 'uppercase' as const,
    },
    editButton: {
      padding: '4px',
      borderRadius: '4px',
      cursor: 'pointer',
      background: 'white',
      boxShadow: '0 2px 4px rgba(0,0,0,0.1)',
      border: 'none',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      transition: 'box-shadow 0.1s ease',
      position: 'absolute' as const,
      right: '24px',
      top: '24px',
    },
    addButton: {
      width: '119px',
      height: '30px',
      background: '#FFFFFF',
      borderRadius: '8px',
      border: 'none',
      cursor: 'pointer',
      transition: 'box-shadow 0.2s ease-in-out',
      fontFamily: 'Inter',
      fontStyle: 'normal',
      fontWeight: 400,
      fontSize: '20px',
      lineHeight: '24px',
      color: '#64748B',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
    },
    addButtonContainer: {
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      borderTop: '1px solid #E2E8F0',
      paddingTop: '18px',
    },
    formLabel: {
      fontSize: '14px',
      color: '#64748B',
      marginBottom: '4px',
      display: 'block',
    },
    formInput: {
      width: '100%',
      padding: '8px',
      border: '1px solid #E2E8F0',
      borderRadius: '4px',
      backgroundColor: '#FFFFFF',
      fontFamily: 'Inter',
      fontSize: '14px',
    },
    formInputReadOnly: {
      width: '100%',
      padding: '8px',
      border: '1px solid #E2E8F0',
      borderRadius: '4px',
      backgroundColor: '#F8FAFC',
      fontFamily: 'Inter',
      fontSize: '14px',
    },
  };