app = "readyroom"
primary_region = "yyz"

[build]

[env]
  NODE_ENV = "production"
  SERVER_PORT = "3001"

[[services]]
  internal_port = 3001
  processes = ["app"]
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["http", "tls"]

[experimental]
  auto_rollback = true